CREATE TABLE USERS (
     id_user BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     email varchar(50) NOT NULL,
     username VARCHAR(50) NOT NULL UNIQUE,
     password VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE SPECIES (
    id_species BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(100) NOT NULL,
    description TEXT
);

CREATE TABLE CARTA (
    id_carta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    species_id BIGINT NOT NULL,
    biological_type VARCHAR(50) NOT NULL,
    diet_usage VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    scientific_name VARCHAR(150),
    description TEXT,
    habitat VARCHAR(255),
    extinction_status VARCHAR(50) NOT NULL,
    curiosity TEXT,

    CONSTRAINT fk_species
        FOREIGN KEY (species_id)
        REFERENCES SPECIES(id_species)
);

CREATE TABLE QUESTIONS (
    question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question VARCHAR(300) NOT NULL,
    category VARCHAR(50) NOT NULL,
    correct_answer VARCHAR(300) NOT NULL,
    incorrect_answer1 VARCHAR(300) NOT NULL,
    incorrect_answer2 VARCHAR(300) NOT NULL,
    incorrect_answer3 VARCHAR(300) NOT NULL
);